version: "3.8"

services:
  app:
    build: .
    container_name: codeigniter-app
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=my_database
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/config.inc.php:/var/www/html/config.inc.php

volumes:
  mysql_data:
